[env:digispark-tiny]
platform = atmel-avr
board = digispark-tiny
framework = arduino

; PlatformIO registry: https://registry.platformio.org/libraries/digistump/DigisparkKeyboard
lib_deps =
    digistump/DigisparkKeyboard@^1.0.0

upload_protocol = micronucleus
